"use client";

import React from "react";
import { AppShell } from "@/components/layout/app-shell";
import { StatusBadge } from "@/components/shared/status-badge";
import { CheckSquare, Clock, ShieldCheck } from "lucide-react";

export default function RecommendationsPage() {
  return (
    <AppShell>
      <div className="space-y-6 text-left">
        <div className="border-b border-[var(--border-default)] pb-4">
          <h1 className="text-xl font-bold tracking-tight text-[var(--text-primary)]">
            Safety & Maintenance Recommendations
          </h1>
          <p className="text-xs text-[var(--text-tertiary)] mt-1">
            Operational action queue generated by AI reasoning for human biomedical professionals.
          </p>
        </div>

        <div className="rounded-lg bg-blue-50 border border-blue-200 p-3.5 flex items-start gap-3 text-xs text-blue-800">
          <ShieldCheck className="h-4 w-4 text-blue-600 shrink-0 mt-0.5" />
          <div>
            <strong className="text-blue-700 block mb-0.5">HUMAN-IN-THE-LOOP OPERATIONAL WORKFLOW</strong>
            <p className="text-[0.68rem] text-blue-800/90 leading-relaxed">
              Recommendations below are generated by the Squad B AI agent to assist biomedical engineers. The platform does NOT automatically execute maintenance; human engineering verification remains required.
            </p>
          </div>
        </div>

        <div className="p-5 rounded-xl bg-[var(--surface-1)] border border-[var(--border-default)] space-y-4">
          <div className="flex items-center justify-between border-b border-[var(--border-default)] pb-3 mb-2">
            <div>
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-700">
                Recommended Action Items — Device DEV-88401
              </h3>
              <p className="text-[0.65rem] text-[var(--text-tertiary)]">Target Asset: Smart Infusion Pump System (Risk Score: 87 / 100)</p>
            </div>
            <StatusBadge variant="critical">3 Pending Actions</StatusBadge>
          </div>

          <div className="space-y-3 font-sans">
            {[
              {
                step: 1,
                title: "Safety & Operational Audit Inspection",
                priority: "critical",
                timeframe: "Immediate (< 4 hours)",
                role: "Biomedical Engineering",
                reason: "CatBoost model predicts high future-event risk (0.87). Immediate physical inspection of occlusion pressure calibration and battery state required.",
              },
              {
                step: 2,
                title: "Historical Event & Safety Notice Audit",
                priority: "critical",
                timeframe: "Within 24 Hours",
                role: "Biomedical Engineering",
                reason: "2 registered field safety notices and 1 recall notice in model history. Cross-verify serial number against manufacturer safety bulletins.",
              },
              {
                step: 3,
                title: "Increased Diagnostic Monitoring & Escalation",
                priority: "critical",
                timeframe: "Within 48 Hours",
                role: "Clinical Engineering Safety Team",
                reason: "Escalate asset status in risk tracking registry until formal biomedical engineering sign-off is completed.",
              },
            ].map((item) => (
              <div key={item.step} className="p-4 rounded-lg bg-[var(--surface-2)] border border-[var(--border-default)] space-y-2">
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-2.5">
                    <div className="flex h-6 w-6 items-center justify-center rounded bg-[var(--surface-1)] text-xs font-mono font-bold text-blue-600 border border-[var(--border-default)]">
                      {item.step}
                    </div>
                    <div>
                      <h4 className="text-xs font-bold text-[var(--text-primary)]">{item.title}</h4>
                      <p className="text-[0.65rem] text-[var(--text-tertiary)] font-mono mt-0.5">
                        Responsible Role: <strong className="text-slate-700">{item.role}</strong>
                      </p>
                    </div>
                  </div>

                  <StatusBadge variant={item.priority}>{item.priority}</StatusBadge>
                </div>

                <p className="text-xs text-[var(--text-secondary)] leading-relaxed bg-[var(--surface-2)] p-2.5 rounded border border-[var(--border-subtle)]">
                  {item.reason}
                </p>

                <div className="flex items-center justify-between text-[0.65rem] font-mono text-[var(--text-tertiary)] pt-1 border-t border-[var(--border-subtle)]">
                  <span className="flex items-center gap-1">
                    <Clock className="h-3 w-3 text-[var(--text-tertiary)]" /> Timeframe: <strong className="text-[var(--text-secondary)]">{item.timeframe}</strong>
                  </span>
                  <span className="text-blue-600">Requires Human Authorization</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </AppShell>
  );
}
